# Generated by Django 4.2.28 on 2026-03-12 19:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('bio', models.TextField(blank=True)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('non_binary', 'Non-Binary'), ('prefer_not_to_say', 'Prefer Not to Say')], max_length=20)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('profile_picture', models.ImageField(blank=True, upload_to='profile_pics')),
                ('looking_for', models.CharField(blank=True, choices=[('romantic', 'Romantic'), ('platonic', 'Platonic'), ('both', 'Both')], max_length=20)),
                ('matching_preference', models.CharField(blank=True, choices=[('top_artists', 'Top Artists'), ('genre', 'Genre'), ('era', 'Era'), ('opposite_genre', 'Opposite Genre')], max_length=20)),
                ('preferred_min_age', models.IntegerField(blank=True, null=True)),
                ('preferred_max_age', models.IntegerField(blank=True, null=True)),
                ('preferred_gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('non_binary', 'Non-Binary'), ('prefer_not_to_say', 'Prefer Not to Say')], max_length=20)),
                ('preferred_location', models.CharField(blank=True, max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
