# Generated by Django 4.2.28 on 2026-03-25 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="age",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
