# Generated by Django 4.2.28 on 2026-03-26 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_alter_userprofile_age"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="matching_preference",
            field=models.CharField(
                blank=True,
                choices=[("top_artists", "Top Artists"), ("era", "Era")],
                max_length=20,
            ),
        ),
    ]
