# Generated by Django 4.2.28 on 2026-03-26 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_alter_userprofile_matching_preference"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="matching_preference",
            field=models.CharField(
                blank=True,
                choices=[
                    ("top_artists", "Top Artists"),
                    ("genre", "Genre"),
                    ("era", "Era"),
                    ("opposite_genre", "Opposite Genre"),
                ],
                max_length=20,
            ),
        ),
    ]
